spring:
  datasource:
    url: jdbc:mysql://localhost/ii?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: ii
    password: ii

OPENSHIFT_DATA_DIR: '/'
OPENSHIFT_BASE_URL: 'http://ii.ayfaar.org/'

logging:
  level:
    org.ayfaar: trace
server:
  ssl:
    key-store: D:\projects\ayfaar\ii-app\keystore.p12
