OPENSHIFT_EXTMYSQL_DB_HOST: 127.0.0.1
OPENSHIFT_EXTMYSQL_DB_USERNAME: root
OPENSHIFT_EXTMYSQL_DB_PASSWORD:
OPENSHIFT_EXTMYSQL_DB_PORT: 3306
OPENSHIFT_EXTAPP_NAME: ii
OPENSHIFT_HOMEDIR:
OPENSHIFT_DATA_DIR: '\'